services:
  crawler:
    build: crawler/.
    platform: linux/amd64
    env_file:
      - .env
    container_name: naf_crawler
    volumes:
      - ./crawler:/app
    ports: []
  analyzer:
    build: analyzer/.
    platform: linux/amd64
    env_file:
      - .env
    container_name: naf_analyzer
    volumes:
      - ./analyzer:/app
  pgadmin:
    image: dpage/pgadmin4
    container_name: naf_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: epics@epics.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  naf_db:
    image: postgres:15
    container_name: naf_db
    restart: always
    environment:
      POSTGRES_USER: epics
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgadmin-data:
  pgdata:
