version: "3.8"

services:
  crawler:
    build: crawler/.
    env_file:
      - .env
    image: naf_crawler
    container_name: naf_crawler
    working_dir: /app
    volumes:
      - ./crawler:/app
    ports: []
    command: ["npm", "run", "start"]
  analyzer:
    build: analyzer/.
    env_file:
      - .env
    image: naf_analyzer
    container_name: naf_analyzer
    working_dir: /app
    volumes:
      - ./analyzer:/app
    command: ["npm", "run", "start"]
