# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: linkedindb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: linkedin_user
      POSTGRES_PASSWORD: linkedin_pass
      POSTGRES_DB: linkedin_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  pgdata:
