export interface AcademyLocation {
  city: string;
  state: string;
  lat: number;
  lon: number;
}

export const ACADEMY_LOCATIONS: AcademyLocation[] = [
  // ALABAMA
  { city: "Atmore", state: "AL", lat: 31.025837, lon: -87.506462 },
  { city: "Birmingham", state: "AL", lat: 33.518589, lon: -86.810356 },

  // ARIZONA
  { city: "Glendale", state: "AZ", lat: 33.548264, lon: -112.191696 },
  { city: "Phoenix", state: "AZ", lat: 33.448376, lon: -112.074036 },

  // CALIFORNIA
  { city: "Azusa", state: "CA", lat: 34.133619, lon: -117.907562 },
  { city: "Burbank", state: "CA", lat: 34.180839, lon: -118.308968 },
  { city: "Compton", state: "CA", lat: 33.895849, lon: -118.220071 },
  { city: "Covina", state: "CA", lat: 34.090009, lon: -117.890339 },
  { city: "Dinuba", state: "CA", lat: 36.543013, lon: -119.38707 },
  { city: "Duarte", state: "CA", lat: 34.139729, lon: -117.977285 },
  { city: "Fresno", state: "CA", lat: 36.7378, lon: -119.787125 },
  { city: "Long Beach", state: "CA", lat: 33.77005, lon: -118.193741 },
  { city: "Los Angeles", state: "CA", lat: 34.052235, lon: -118.243683 },
  { city: "Milpitas", state: "CA", lat: 37.432335, lon: -121.899574 },
  { city: "Monrovia", state: "CA", lat: 34.14806, lon: -118.001945 },
  { city: "Orosi", state: "CA", lat: 36.543563, lon: -119.28929 },
  { city: "Palo Alto", state: "CA", lat: 37.441883, lon: -122.143019 },
  { city: "Pomona", state: "CA", lat: 34.055103, lon: -117.74999 },
  { city: "Porterville", state: "CA", lat: 36.06523, lon: -119.01677 },
  { city: "Tulare", state: "CA", lat: 36.207728, lon: -119.347338 },
  { city: "Vallejo", state: "CA", lat: 38.104087, lon: -122.256637 },

  // COLORADO
  { city: "Greeley", state: "CO", lat: 40.423314, lon: -104.709132 },

  // CONNECTICUT
  { city: "East Hartford", state: "CT", lat: 41.763421, lon: -72.612831 },
  { city: "Hartford", state: "CT", lat: 41.765804, lon: -72.673372 },
  { city: "New Britain", state: "CT", lat: 41.66121, lon: -72.779541 },
  { city: "Stamford", state: "CT", lat: 41.05343, lon: -73.538734 },

  // WASHINGTON DC
  { city: "Washington", state: "DC", lat: 38.89511, lon: -77.03637 },

  // DELAWARE
  { city: "Felton", state: "DE", lat: 39.009001, lon: -75.577703 },
  { city: "New Castle", state: "DE", lat: 39.662057, lon: -75.566816 },
  { city: "Newark", state: "DE", lat: 39.683723, lon: -75.749657 },
  { city: "Smyrna", state: "DE", lat: 39.299833, lon: -75.604372 },
  { city: "Wilmington", state: "DE", lat: 39.739072, lon: -75.539787 },

  // FLORIDA
  { city: "Fort Lauderdale", state: "FL", lat: 26.122439, lon: -80.137317 },
  { city: "Largo", state: "FL", lat: 27.909466, lon: -82.787324 },
  { city: "Miami", state: "FL", lat: 25.761681, lon: -80.191788 },
  { city: "Naples", state: "FL", lat: 26.142036, lon: -81.794813 },
  { city: "Orlando", state: "FL", lat: 28.538336, lon: -81.379234 },
  { city: "Riverview", state: "FL", lat: 27.86614, lon: -82.32648 },
  { city: "Sanford", state: "FL", lat: 28.802491, lon: -81.269409 },
  { city: "Tampa", state: "FL", lat: 27.950575, lon: -82.457178 },
  { city: "West Palm Beach", state: "FL", lat: 26.715342, lon: -80.053374 },

  // HAWAII
  { city: "Honolulu", state: "HI", lat: 21.306944, lon: -157.858337 },

  // IDAHO
  { city: "Idaho Falls", state: "ID", lat: 43.491651, lon: -112.033964 },
  { city: "Pocatello", state: "ID", lat: 42.871303, lon: -112.445534 },

  // INDIANA
  { city: "Sellersburg", state: "IN", lat: 38.398681, lon: -85.754963 },

  // KANSAS
  { city: "Kansas City", state: "KS", lat: 39.114053, lon: -94.627464 },

  // LOUISIANA
  { city: "Baton Rouge", state: "LA", lat: 30.451468, lon: -91.187147 },
  { city: "Lafayette", state: "LA", lat: 30.22409, lon: -92.019842 },
  { city: "New Orleans", state: "LA", lat: 29.951066, lon: -90.071532 },

  // MARYLAND
  { city: "Baltimore", state: "MD", lat: 39.290385, lon: -76.612189 },
  { city: "Bel Air", state: "MD", lat: 39.53594, lon: -76.348293 },
  { city: "Ellicott City", state: "MD", lat: 39.267328, lon: -76.798306 },
  { city: "Rockville", state: "MD", lat: 39.083997, lon: -77.152758 },
  { city: "Upper Marlboro", state: "MD", lat: 38.815112, lon: -76.749413 },
  { city: "Westminster", state: "MD", lat: 39.575379, lon: -76.995814 },

  // MASSACHUSETTS
  { city: "Chicopee", state: "MA", lat: 42.148704, lon: -72.607867 },
  { city: "New Bedford", state: "MA", lat: 41.636215, lon: -70.934204 },
  { city: "Roxbury", state: "MA", lat: 42.329591, lon: -71.094215 },

  // MICHIGAN
  { city: "Detroit", state: "MI", lat: 42.331427, lon: -83.045754 },
  { city: "Farmington", state: "MI", lat: 42.464484, lon: -83.376322 },
  { city: "Flint", state: "MI", lat: 43.012527, lon: -83.687457 },
  { city: "Grand Rapids", state: "MI", lat: 42.963359, lon: -85.668086 },
  { city: "Hazel Park", state: "MI", lat: 42.462812, lon: -83.104372 },
  { city: "Oak Park", state: "MI", lat: 42.459477, lon: -83.182377 },
  { city: "Pontiac", state: "MI", lat: 42.638921, lon: -83.291047 },
  { city: "Redford", state: "MI", lat: 42.383372, lon: -83.296597 },
  { city: "Rochester", state: "MI", lat: 42.680588, lon: -83.133824 },
  { city: "Southfield", state: "MI", lat: 42.473368, lon: -83.221873 },

  // MINNESOTA
  { city: "Saint Paul", state: "MN", lat: 44.953703, lon: -93.089958 },

  // MISSOURI
  { city: "Hazelwood", state: "MO", lat: 38.771938, lon: -90.370671 },
  { city: "Jennings", state: "MO", lat: 38.728938, lon: -90.272335 },
  { city: "University City", state: "MO", lat: 38.655603, lon: -90.309728 },

  // NEVADA
  { city: "Las Vegas", state: "NV", lat: 36.169941, lon: -115.139832 },

  // NEW HAMPSHIRE
  { city: "Merrimack", state: "NH", lat: 42.86509, lon: -71.493395 },

  // NEW JERSEY
  { city: "Elizabeth", state: "NJ", lat: 40.663991, lon: -74.2107 },
  { city: "Fort Lee", state: "NJ", lat: 40.850933, lon: -73.970138 },
  { city: "Jersey City", state: "NJ", lat: 40.717754, lon: -74.043143 },
  { city: "Passaic", state: "NJ", lat: 40.856766, lon: -74.128476 },
  { city: "Wayne", state: "NJ", lat: 40.925372, lon: -74.276544 },

  // NEW YORK
  { city: "Angola", state: "NY", lat: 42.638116, lon: -79.027823 },
  { city: "Cheektowaga", state: "NY", lat: 42.903396, lon: -78.754753 },
  { city: "Clarence", state: "NY", lat: 42.980614, lon: -78.591702 },
  { city: "Depew", state: "NY", lat: 42.911724, lon: -78.692807 },
  { city: "Elmira", state: "NY", lat: 42.089796, lon: -76.807733 },
  { city: "Floral Park", state: "NY", lat: 40.723713, lon: -73.704853 },
  { city: "Garnerville", state: "NY", lat: 41.204538, lon: -73.986527 },
  { city: "Grand Island", state: "NY", lat: 43.033119, lon: -78.962812 },
  { city: "Hamburg", state: "NY", lat: 42.715892, lon: -78.829476 },
  { city: "Lancaster", state: "NY", lat: 42.900621, lon: -78.670311 },
  { city: "Middletown", state: "NY", lat: 41.445927, lon: -74.422934 },
  { city: "Monticello", state: "NY", lat: 41.653427, lon: -74.689888 },
  { city: "New York", state: "NY", lat: 40.712776, lon: -74.005974 },
  { city: "North Tonawanda", state: "NY", lat: 43.03867, lon: -78.864203 },
  { city: "Northport", state: "NY", lat: 40.901488, lon: -73.343727 },
  { city: "Salamanca", state: "NY", lat: 42.157286, lon: -78.715034 },
  { city: "West Seneca", state: "NY", lat: 42.83673, lon: -78.799757 },
  { city: "Westbury", state: "NY", lat: 40.755656, lon: -73.587067 },
  { city: "Wilson", state: "NY", lat: 43.309226, lon: -78.824479 },
  { city: "Yonkers", state: "NY", lat: 40.93121, lon: -73.898747 },
  { city: "Youngstown", state: "NY", lat: 43.248391, lon: -79.050324 },

  // NORTH CAROLINA
  { city: "Asheboro", state: "NC", lat: 35.707914, lon: -79.813644 },
  { city: "Burlington", state: "NC", lat: 36.095691, lon: -79.437799 },
  { city: "Cary", state: "NC", lat: 35.79154, lon: -78.781116 },
  { city: "Charlotte", state: "NC", lat: 35.227087, lon: -80.843127 },
  { city: "Concord", state: "NC", lat: 35.408752, lon: -80.579511 },
  { city: "Durham", state: "NC", lat: 35.994033, lon: -78.898619 },
  { city: "Fayetteville", state: "NC", lat: 35.052664, lon: -78.878358 },
  { city: "Mooresville", state: "NC", lat: 35.584859, lon: -80.810072 },
  { city: "Sanford", state: "NC", lat: 35.479876, lon: -79.180299 },
  { city: "Smithfield", state: "NC", lat: 35.508488, lon: -78.339735 },
  { city: "Wilmington", state: "NC", lat: 34.225726, lon: -77.94471 },
  { city: "Winston-Salem", state: "NC", lat: 36.099861, lon: -80.244217 },

  // OHIO
  { city: "Columbus", state: "OH", lat: 39.961176, lon: -82.998794 },

  // PENNSYLVANIA
  { city: "Scranton", state: "PA", lat: 41.408969, lon: -75.662412 },
  { city: "Uniontown", state: "PA", lat: 39.900078, lon: -79.716431 },

  // PUERTO RICO
  { city: "Mayaguez", state: "PR", lat: 18.201349, lon: -67.139625 },

  // RHODE ISLAND
  { city: "North Kingstown", state: "RI", lat: 41.551491, lon: -71.466164 },
  { city: "Providence", state: "RI", lat: 41.824, lon: -71.412834 },
  { city: "Wood River Junction", state: "RI", lat: 41.437877, lon: -71.702845 },

  // SOUTH CAROLINA
  { city: "Columbia", state: "SC", lat: 34.00071, lon: -81.034814 },

  // SOUTH DAKOTA
  { city: "Sioux Falls", state: "SD", lat: 43.544595, lon: -96.731103 },

  // TEXAS
  { city: "Carrollton", state: "TX", lat: 32.975642, lon: -96.889963 },
  { city: "Dallas", state: "TX", lat: 32.776664, lon: -96.796988 },
  { city: "El Paso", state: "TX", lat: 31.761878, lon: -106.485022 },
  { city: "Richardson", state: "TX", lat: 32.948181, lon: -96.72972 },

  // VIRGIN ISLANDS
  { city: "Christiansted", state: "VI", lat: 17.746639, lon: -64.703197 },
  { city: "St. Thomas", state: "VI", lat: 18.338096, lon: -64.894094 },

  // VIRGINIA
  { city: "Alexandria", state: "VA", lat: 38.804836, lon: -77.046921 },

  // WASHINGTON
  { city: "Federal Way", state: "WA", lat: 47.322322, lon: -122.312622 },
  { city: "Seattle", state: "WA", lat: 47.606209, lon: -122.332071 },

  // WISCONSIN
  { city: "Milwaukee", state: "WI", lat: 43.038902, lon: -87.906471 },
];

export interface PartnerCompany {
  name: string;
}

export const PARTNERED_COMPANIES: PartnerCompany[] = [
  { name: "AAMC" },
  { name: "ACTE" },
  { name: "Advance CTE" },
  { name: "AICPA" },
  { name: "AHLA" },
  { name: "American Accounting Association" },
  { name: "Canva" },
  { name: "Code.org" },
  { name: "CSTA" },
  { name: "CYBER.ORG" },
  { name: "Discover Engineering" },
  { name: "EarSketch" },
  { name: "EVERFI" },
  { name: "Federal Reserve Bank of St. Louis" },
  { name: "GTTP" },
  { name: "HOSA" },
  { name: "KPMG" },
  { name: "LabXchange" },
  { name: "Marriott International" },
  { name: "NCHSE" },
  { name: "NGPF" },
  { name: "NFTE" },
  { name: "PLTW" },
  { name: "SAP" },
  { name: "Verizon" },
  { name: "Wilmington University" },
];

export interface HighSchool {
  name: string;
}

export const HIGH_SCHOOLS: HighSchool[] = [
  { name: "A. I. duPont High School" },
  { name: "Academy of Finance and Enterprise" },
  { name: "Academy of The Americas" },
  { name: "Advance Math and Science IV High School" },
  { name: "Albert Einstein High School" },
  { name: "Alexandria City High School" },
  { name: "Alonzo and Tracy Mourning Senior High School" },
  { name: "American Senior High School" },
  { name: "Anacostia High School" },
  { name: "Applications & Research Lab" },
  { name: "Armwood High School" },
  { name: "Atlantic High School" },
  { name: "Atlantic Technical College and Technical High School" },
  { name: "Aubrey Rogers High School" },
  { name: "Audubon Technology and Communication High School" },
  { name: "Azusa High School" },
  { name: "Ballard High School" },
  { name: "Ballou High School" },
  { name: "Barbara Goleman Senior High School" },
  { name: "Barron Collier High School" },
  { name: "Bay View High School" },
  { name: "Beecher High School" },
  { name: "BERKNER H S" },
  { name: "Bishop Ward High School" },
  { name: "Blanche Ely High School" },
  { name: "Booker T. Washington Senior High" },
  { name: "Boulder Creek High School" },
  { name: "Boyd Anderson High School" },
  { name: "Brandon High School" },
  { name: "Brooklyn Academy of Global Finance High School" },
  { name: "Brooklyn Lab School" },
  { name: "Browning High School" },
  { name: "Bryan Adams High School" },
  { name: "Burbank High School" },
  { name: "Bulkeley High School" },
  { name: "Business of Sports School" },
  { name: "Butler High School" },
  { name: "Calvin Coolidge High School" },
  { name: "Carencro High School" },
  { name: "Career & Technical Education Academy" },
  { name: "Career & Technical Education Center" },
  { name: "Caesar Rodney High School" },
  { name: "Cass Technical High School" },
  { name: "Central High School" },
  { name: "Centennial High" },
  { name: "Charlotte Amalie High School" },
  { name: "Charlotte Engineering Early College" },
  { name: "Charter Oak High School" },
  { name: "Chariho Regional High School" },
  { name: "Chicopee High" },
  { name: "Clark High School" },
  { name: "Clayton High" },
  { name: "Columbia Heights Educational Campus" },
  { name: "Columbia High School" },
  { name: "Como Park High School" },
  { name: "Communication Media Arts HS" },
  { name: "Compton High School" },
  { name: "Concord High School" },
  { name: "Coral Gables Senior High School" },
  { name: "Coral Reef Senior High School" },
  { name: "Cox Mill High School" },
  { name: "Crooms Academy of Information Technology" },
  { name: "Crossland High School" },
  { name: "Cutler Bay Senior High School" },
  { name: "Damascus High School" },
  { name: "David W. Carter High School" },
  { name: "Davis Aerospace Technical High School" },
  { name: "Decatur High School" },
  { name: "Deer Valley High School" },
  { name: "Deerfield Beach High School" },
  { name: "Delaware Military Academy" },
  { name: "Denby High School" },
  { name: "Dickinson High School" },
  { name: "Dillard High School" },
  { name: "Dinuba High School" },
  { name: "Dover High School" },
  { name: "Douglas Byrd High School" },
  { name: "Dr. Henry A. Wise, Jr. High School" },
  { name: "Dr. Jorge Alvarez HS" },
  { name: "Dr. Michael M. Krop Senior High School" },
  { name: "Duarte High School" },
  { name: "Dunbar High School" },
  { name: "Duncan High School" },
  { name: "DSCYF" },
  { name: "East Boston High School" },
  { name: "East English Village Preparatory Academy at Finney" },
  { name: "East Forsyth High School" },
  { name: "East Hartford High School" },
  { name: "East Meadow High School" },
  { name: "Eastwood High School" },
  { name: "Edison High School" },
  { name: "Edgewater High School" },
  { name: "Edgewood High School" },
  { name: "E.E. Smith High School" },
  { name: "Elvira M. Colon Negron" },
  { name: "Elmira High School" },
  { name: "Emmett J. Conrad High School" },
  { name: "Enloe High School" },
  { name: "Escambia Co High Sch" },
  { name: "Escuela Superior Benito Cerezo Vázquez" },
  { name: "Federal Way High School" },
  { name: "Felix Varela Senior High School" },
  { name: "Ferris High School" },
  { name: "Florence High School" },
  { name: "Forest Hill Community High School" },
  { name: "Foshay Learning Center High School" },
  { name: "Fort Lee High School" },
  { name: "Friendship Collegiate Academy" },
  { name: "Friendship Tech Prep" },
  { name: "Fresno High School" },
  { name: "Frederick Douglass Academy at Northern High School" },
  { name: "Gaithersburg High School" },
  { name: "George Washington Carver High School" },
  { name: "Glasgow High School" },
  { name: "Golden Gate High School" },
  { name: "Granite Hills High School" },
  { name: "Gray's Creek High School" },
  { name: "Grand Island Senior High School" },
  { name: "G. Holmes Braddock" },
  { name: "Gulf Coast High School" },
  { name: "Hamburg High School" },
  { name: "Harmony Magnet Academy" },
  { name: "Hartford Public High School (HPHS)" },
  { name: "Hawthorne Academy of Health Science" },
  { name: "Hazel Park High School" },
  { name: "Henry Ford High School" },
  { name: "Henry M. Gunn High School" },
  { name: "Hialeah Gardens High School" },
  { name: "Hialeah High School" },
  { name: "Hickory Ridge High School" },
  { name: "Hillcrest High School" },
  { name: "Homestead Senior High School" },
  { name: "Hope Academy of West Michigan" },
  { name: "Huffman High School" },
  { name: "Ivanna Eudora Kean High School" },
  { name: "Independence High School" },
  { name: "Innovation High School" },
  { name: "Jackson-Olin High School" },
  { name: "Jackson-Reed High School" },
  { name: "Jacqueline Kennedy Onassis High School" },
  { name: "James Madison Academic Campus" },
  { name: "James Madison High School" },
  { name: "Jalen Rose Leadership Academy" },
  { name: "Jay M Robinson High School" },
  { name: "Jennings Senior High" },
  { name: "John A. Ferguson Senior High School" },
  { name: "John Burroughs High School" },
  { name: "John Dwyer Technology Academy School No. 82" },
  { name: "John I. Leonard High School" },
  { name: "John T Hoggard High" },
  { name: "Juanita Sanchez Educational Complex" },
  { name: "J Christian Bollwage Finance Academy" },
  { name: "Justin F. Kimball High School" },
  { name: "KIPP DC College Preparatory" },
  { name: "KIPP DC Legacy College Preparatory" },
  { name: "Kid's Community College Preparatory High School" },
  { name: "King High School" },
  { name: "Lake Brantley High School" },
  { name: "Lake Forest High School" },
  { name: "Lake Shore Central High School" },
  { name: "Lancaster High School" },
  { name: "Largo High School" },
  { name: "Las Americas ASPIRA Academy" },
  { name: "Laurel Highlands Senior High School" },
  { name: "Laurel High School" },
  { name: "Lee County High School" },
  { name: "Lee M. Thurston High School" },
  { name: "Lely High School" },
  { name: "Lewiston-Porter Central School District - High School" },
  { name: "Lighthouse Academy" },
  { name: "Lincoln High School" },
  { name: "Long Island city high School" },
  { name: "Los Angeles High School" },
  { name: "MCCLUER HIGH" },
  { name: "MCCLUER NORTH HIGH" },
  { name: "Maya Angelou Public Charter High School" },
  { name: "Marjory Stoneman Douglas High School" },
  { name: "Marshall High School" },
  { name: "Martin Luther King, Jr. High School" },
  { name: "Maryvale High School" },
  { name: "Maui High School" },
  { name: "McKinley Technology High School" },
  { name: "McLane High School" },
  { name: "Merrimack High School" },
  { name: "Miami Beach Senior High School" },
  { name: "Miami Central Senior High School" },
  { name: "Miami Edison Senior High School" },
  { name: "Miami Jackson Senior High School" },
  { name: "Miami Killian Senior High School" },
  { name: "Miami Lakes Educational Center and Technical College" },
  { name: "Miami Norland Senior High School" },
  { name: "Miami Northwestern Senior High School" },
  { name: "Miami Southridge Senior High School" },
  { name: "Miami Springs Senior High School" },
  { name: "Milford High School" },
  { name: "Milpitas High School" },
  { name: "Mission Oak High School" },
  { name: "Middletown High School" },
  { name: "Monache High School" },
  { name: "Monarch High School" },
  { name: "Monrovia High School" },
  { name: "Monticello High School" },
  { name: "Mooresville High School" },
  { name: "Mount Pleasant Early College & Career Academy" },
  { name: "Mountain Ridge High School" },
  { name: "Mumford High School" },
  { name: "Naples High School" },
  { name: "National Academy Foundation High School" },
  { name: "New Bedford High School" },
  { name: "New Britain High School" },
  { name: "New Hyde Park Memorial High School" },
  { name: "New Utrecht High School" },
  { name: "Newman Smith High School" },
  { name: "North Dallas High School" },
  { name: "North Johnston High School" },
  { name: "North Kingstown High School" },
  { name: "North Miami Beach Senior High School" },
  { name: "North Miami Senior High School" },
  { name: "North Tonawanda High School" },
  { name: "North Division High School" },
  { name: "North Forsyth High School" },
  { name: "North Rockland High School" },
  { name: "Northwest Cabarrus High School" },
  { name: "Northwest High School" },
  { name: "Northport High School" },
  { name: "Northeast High School" },
  { name: "Northridge High School" },
  { name: "Oak Park High School" },
  { name: "Odyssey Charter High School" },
  { name: "Olympic Heights Community High School" },
  { name: "Olympic High School" },
  { name: "Orchard Park High School" },
  { name: "Orosi High School" },
  { name: "Osborn High School" },
  { name: "Ottawa Hills High School" },
  { name: "Oxon High School" },
  { name: "Paint Branch High School" },
  { name: "Palmetto Ridge High School" },
  { name: "Palomares High School" },
  { name: "Palo Alto High School" },
  { name: "Passaic County Technical Institute" },
  { name: "Passaic High School" },
  { name: "Pathways Academy of Technology & Design" },
  { name: "PEARCE H S" },
  { name: "Pershing High School" },
  { name: "Phelps A.C.E. High School" },
  { name: "Pine Forest High School" },
  { name: "Pinson Valley High School" },
  { name: "Piper High School" },
  { name: "Pontiac High School" },
  { name: "Porterville High School" },
  { name: "Porterville Military Academy" },
  { name: "Portneuf Valley Technical Education and Career Campus" },
  { name: "Princeton High" },
  { name: "Ramsay High School" },
  { name: "Raymond S. Kellis High School" },
  { name: "Renaissance High School" },
  { name: "River Terrace Education Campus" },
  { name: "Robert Morgan Educational Center and Technical Col" },
  { name: "Rochester High School" },
  { name: "Roosevelt High School" },
  { name: "Ronald Reagan High School" },
  { name: "Salamanca High School" },
  { name: "Sanderson High School AOF" },
  { name: "Scranton High School" },
  { name: "Scotlandville Magnet High School" },
  { name: "Shades Valley High School" },
  { name: "Silver Creek High School" },
  { name: "Silver Lake High School" },
  { name: "Skyline High School & Career Development Center" },
  { name: "Smithfield-Selma High School" },
  { name: "Smyrna High School" },
  { name: "South Dade Senior High School" },
  { name: "South Division High School" },
  { name: "Southeast Raleigh Magnet High School" },
  { name: "Southeastern High School" },
  { name: "Southern Lee High School" },
  { name: "Southfield High School for the Arts & Technology" },
  { name: "Southwest Miami Senior High School" },
  { name: "SPOTO HIGH SCHOOL" },
  { name: "Springbrook High School" },
  { name: "St. Croix Central High School" },
  { name: "St. Croix Educational Complex" },
  { name: "STEAM High School" },
  { name: "Steinbrenner High School" },
  { name: "Stranahan High School" },
  { name: "Strathmore High School" },
  { name: "Sunset High School" },
  { name: "Susan E. Wagner High School" },
  { name: "Sussex Central High School" },
  { name: "Sunnyside High School" },
  { name: "Thomas Jefferson High School" },
  { name: "Thomas S. Wootton High School" },
  { name: "Todd Beamer High School" },
  { name: "Tottenville High School" },
  { name: "Trinity High School" },
  { name: "Tulare Union High School" },
  { name: "Tulare Western High School" },
  { name: "Vallejo High School" },
  { name: "Valley High School" },
  { name: "Village Academy High School" },
  { name: "Waipahu High School" },
  { name: "Walter M. Williams High School" },
  { name: "Warren Easton Charter High School" },
  { name: "Washington High School of Information Technology" },
  { name: "Weaver High School" },
  { name: "Wenonah High School" },
  { name: "West Mecklenberg High School" },
  { name: "West Scranton High School" },
  { name: "West Seneca East Senior High School" },
  { name: "Westhill High School" },
  { name: "Westminster High School" },
  { name: "Westover High School" },
  { name: "Western International High School" },
  { name: "Wheaton High School" },
  { name: "William H. Turner Technical Arts High School" },
  { name: "William Penn High School" },
  { name: "Wilmer-Hutchins High School" },
  { name: "Wilson High School" },
  { name: "Wilmington University" },
  { name: "W. H. Adamson High School" },
  { name: "W. T. Clarke High School" },
  { name: "W. T. White High School" },
  { name: "Woodbridge High School" },
  { name: "Woodson High School" },
  { name: "Woodlawn High School" },
  { name: "W.W. Samuell High School" },
];

export const DEFAULT_WEIGHTS = {
  highSchool: 0.25,
  internship: 0.2,
  currentJob: 0.15,
  proximityUnder50mi: 0.1,
  proximity50to100mi: 0.05,
} as const;

/*
TEMPORARY ACTION THRESHOLDS; replace later when model is trained
 */
export const TEMP_ACTION_BANDS = {
  STRONG: 0.75,
  PROBABLE: 0.65,
  REVIEW: 0.55,
};
